[package]
name = "plugin_api"
version = "0.1.0"
authors = ["andylokandy <andylokandy@hotmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
rustc_version = "0.3.0"
ignore = "0.4"
checksums = "0.6"
